feat: prod&demo deploy
Informasjonsforvaltning/catalog-view-api pull request #35
Opened 2023-11-09 13:38 UTC by NilsOveTen

resolve #25

2023-11-10 14:42 UTC, jeffreiffers requested changes

2023-11-10 14:42 UTC, jeffreiffers commented on .github/workflows/deploy-prod&demo.yaml
> +    needs: [ build-catalog-view-api, deploy-prod ]
```suggestion
    needs: [deploy-prod ]
```

2023-11-10 14:42 UTC, jeffreiffers commented on deploy/prod/ingress.yaml
> +    - host: catalog-view.api.demo.fellesdatakatalog.digdir.no
```suggestion
    - host: catalog-view.api.fellesdatakatalog.digdir.no
```

2023-11-10 14:42 UTC, jeffreiffers commented on deploy/demo/kustomization.yaml
> +namespace: prod
```suggestion
namespace: demo
```

2023-11-10 14:42 UTC, jeffreiffers commented on deploy/demo/ingress.yaml
> +    - host: catalog-view.api.fellesdatakatalog.digdir.no
```suggestion
    - host: catalog-view.api.demo.fellesdatakatalog.digdir.no
```

2023-11-10 14:42 UTC, jeffreiffers commented on deploy/prod/kustomization.yaml
> +namespace: demo
```suggestion
namespace: prod
```

2023-11-13 11:29 UTC, terjesyl requested changes

2023-11-13 11:29 UTC, terjesyl commented on src/main/kotlin/no/digdir/catalog_view_api/service/AsymmetricKeyJwtGrantGenerator.java
> +        String aliasPassword = "aliaspassword";
fiiiks

2023-11-13 12:06 UTC, terjesyl approved these changes

2023-11-14 09:32 UTC, valosnah approved these changes

2023-11-20 09:04 UTC, terjesyl commented
Skal denne merges og deployes? Trenger godkjenning fra @jeffreiffers i så fall.

2023-11-20 09:17 UTC, NilsOveTen commented
> Skal denne merges og deployes? Trenger godkjenning fra @jeffreiffers i så fall.

Det det henger mest på er deploy av elasticsearch til demo og prod, det skjer snart-ish

2023-11-21 15:08 UTC, jeffreiffers approved these changes

2023-11-22 11:54 UTC, merged